GET http://localhost:2000/users

###
GET http://localhost:2000/users/2


###
POST http://localhost:2000/user/created
Content-Type: application/json

{ 
  "name":"margarin Manuel",
  "birthYear":1999,
  "age":"F"
}

###
PUT http://localhost:2000/user/update/373c6a
Content-Type: application/json

{
  "name":"Margari",
  "birthYear":1999,
  "age":"M"
}
###
DELETE http://localhost:2000/user/delete/3db5f0
